// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CopyResultJSON(arg1) {
  return window['go']['main']['App']['CopyResultJSON'](arg1);
}

export function Decode(arg1) {
  return window['go']['main']['App']['Decode'](arg1);
}

export function DecodeFile(arg1, arg2) {
  return window['go']['main']['App']['DecodeFile'](arg1, arg2);
}

export function ExportResult(arg1, arg2) {
  return window['go']['main']['App']['ExportResult'](arg1, arg2);
}

export function OpenInputFile() {
  return window['go']['main']['App']['OpenInputFile']();
}
