// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CopyResultJSON(arg1:main.DecodeResult):Promise<void>;

export function Decode(arg1:main.DecodeRequest):Promise<main.DecodeResult>;

export function DecodeFile(arg1:string,arg2:main.DecodeOptions):Promise<main.DecodeResult>;

export function ExportResult(arg1:main.DecodeResult,arg2:string):Promise<main.SaveFileResult>;

export function OpenInputFile():Promise<main.OpenFileResult>;
